# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00003hpgarn\tmp\build\80754af9\rsync-recipes\beautifulsoup4-4.8.0-python_3.7-on-winbuilder, last modified Fri Aug 16 07:23:35 2019
# ------------------------------------------------

package:
    name: beautifulsoup4
    version: 4.8.0
source:
    sha256: 25288c9e176f354bf277c0a10aa96c782a6a18a17122dba2e8cec4a97e03343b
    url: https://pypi.io/packages/source/b/beautifulsoup4/beautifulsoup4-4.8.0.tar.gz
build:
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py37_0
requirements:
    host:
        - ca-certificates 2019.5.15 1
        - certifi 2019.6.16 py37_1
        - openssl 1.1.1c he774522_1
        - pip 19.1.1 py37_0
        - python 3.7.4 h5263a28_0
        - setuptools 41.0.1 py37_0
        - sqlite 3.29.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_4
        - wheel 0.33.4 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - soupsieve
test:
    imports:
        - bs4
about:
    description: 'Beautiful Soup is a library for pulling data out of HTML and XML
        files.

        It provides ways of navigating, searching, and modifying parse trees.

        '
    dev_url: https://code.launchpad.net/beautifulsoup
    doc_source_url: https://github.com/newvem/beautifulsoup4/blob/master/doc/source/index.rst
    doc_url: http://beautiful-soup-4.readthedocs.io/en/latest/
    home: http://www.crummy.com/software/BeautifulSoup/
    license: MIT
    license_family: MIT
    license_file: COPYING.txt
    summary: Python library designed for screen-scraping
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jschueller
        - nehaljwani
